### ISSUE TITLE
Please add this functionality

### ISSUE THREAD

**Issue by Vettic** [moody/Dejunk#144]
Hi please add these functions and options

1. add an option to open the destroy window automatically when bags are opened, (for easy access adding items to inclusions)
2. left click in sell and destroy window should sell or destroy the specific item (I never used the "sell all/destroy all" buttons in the previous version)
3. Left click on the merchant button should open the options, not start selling. (there is already a sell button in the dejunk sell window and it's muscle memory to press a red blizzard-style button for options. Seriously, don't mess with muscle memory.)

the new design is nice and compact, but i'd like to see the functionality restored to where is was in the past an improved even, 
thanks

**Comment by moody** [comment]
Hey

1. I like this, and I think it would make sense to add this functionality as part of the "Auto Junk Frame" option
2. Already on the todo list, but there's some other things I have to find the time to fix first
3. Fair enough. I've been wanting to synchronize the functionality between the merchant and minimap buttons for a while, so this might be a good excuse to do it now

Also, I will (slowly) restore some of Dejunk's old functionality, but definitely not everything. There are quite a few features that I left out when I built the new version of the addon, and that's mostly because the old code had become so bloated and confusing that I found it too difficult/time-consuming to maintain. The goal for now is to avoid reaching that point again.

**Comment by azirale** [comment]
If I may add another flaggable option -- can auto-destroy run when talking to a merchant? That is, after selling everything that can be vendored, everything with no sell price is automatically destroyed.

**Comment by moody** [comment]
> If I may add another flaggable option -- can auto-destroy run when talking to a merchant? That is, after selling everything that can be vendored, everything with no sell price is automatically destroyed.

Unfortunately not. Blizzard has made it so that items can only be destroyed one at a time in response to a hardware event (e.g. executing a chat command, clicking a button, or pressing a key).
